name: Deployment Package Zip

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Create target directory
              run: mkdir -p deploy/visualization

            - name: Include lambda files
              run: |
                # Copy regular Lambda files from src/lambda root
                cp src/lambda/*.py ./deploy/

                # Copy visualization Lambda files to visualization subdirectory
                cp src/lambda/visualization/*.py ./deploy/visualization/

            - name: Include system_prompts
              run: cp src/system_prompts/* ./deploy

            - name: Install dependencies
              run: pip install -r requirements.txt -t ./deploy

            - name: Zip dependencies
              run: zip -r9 ./deployment_package.zip ./
              working-directory: ./deploy

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: deployment-package
                  path: ./deploy/deployment_package.zip
