name: Deployment Package Zip

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'
                  cache-dependency-path: src/lambda/athena/package-lock.json

            - name: Create target directory
              run: mkdir -p deploy/visualization

            - name: Include lambda files
              run: |
                # First copy the Python files from the root lambda directory
                find src/lambda -maxdepth 1 -name "*.py" -exec cp {} ./deploy/ \;

                # Then copy the visualization Python files
                find src/lambda/visualization -name "*.py" -exec cp {} ./deploy/visualization/ \;

            - name: Include system_prompts
              run: |
                # Handle system_prompts directory which may contain files
                if [ -d "src/system_prompts" ]; then
                  find src/system_prompts -type f -exec cp {} ./deploy/ \;
                fi

            - name: Install Python dependencies
              run: pip install -r requirements.txt -t ./deploy

            - name: Build Node.js Athena Lambda package
              run: |
                cd src/lambda/athena
                npm ci --only=production
                # Use consistent timestamps for reproducible builds
                find . -type f -exec touch -t 200001010000.00 {} \;
                zip -Xr9D athena-lambda.zip . -x "*.git*" -x "*.zip" -x "node_modules/.cache/*" -x "package-lock.json"
                # Copy to main directory for Terraform
                cp athena-lambda.zip ../../../main/

            - name: Build Python Forecast Sync Lambda package
              run: |
                # Create forecast sync package directory
                mkdir -p deploy/forecast_sync

                # Copy forecast sync Python files
                cp src/lambda/forecast_sync/*.py deploy/forecast_sync/

                # Install forecast sync dependencies
                pip install -r src/lambda/forecast_sync/requirements.txt -t deploy/forecast_sync/

                # Create ZIP package with consistent timestamps
                cd deploy/forecast_sync
                # Remove compiled Python files
                find . -type f -name "*.pyc" -delete
                find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
                # Set consistent timestamps
                find . -type f -exec touch -t 200001010000.00 {} \;
                zip -Xr9D forecast-sync-lambda.zip . -x "*.git*" -x "*.pyc" -x "__pycache__/*"

                # Copy to main directory for Terraform
                cp forecast-sync-lambda.zip ../../main/

            - name: Zip Python dependencies
              run: |
                # Remove compiled Python files
                find . -type f -name "*.pyc" -delete
                find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
                # Set consistent timestamps for reproducible builds
                find . -type f -exec touch -t 200001010000.00 {} \;
                # Create zip with consistent settings
                zip -Xr9D ./deployment_package.zip ./
              working-directory: ./deploy

            - name: Upload Python deployment package
              uses: actions/upload-artifact@v4
              with:
                  name: deployment-package
                  path: ./deploy/deployment_package.zip

            - name: Upload Athena Lambda package
              uses: actions/upload-artifact@v4
              with:
                  name: athena-lambda-package
                  path: ./main/athena-lambda.zip

            - name: Upload Forecast Sync Lambda package
              uses: actions/upload-artifact@v4
              with:
                  name: forecast-sync-lambda-package
                  path: ./main/forecast-sync-lambda.zip

            - name: Generate Package Hashes
              run: |
                # Generate SHA256 hashes for all packages
                echo "## Lambda Package Hashes" > package-hashes.txt
                echo "Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> package-hashes.txt
                echo "" >> package-hashes.txt

                cd main
                for package in *.zip; do
                  if [[ -f "$package" ]]; then
                    hash=$(sha256sum "$package" | cut -d' ' -f1)
                    echo "${package}: ${hash}" >> ../package-hashes.txt
                  fi
                done

                cd ../deploy
                if [[ -f "deployment_package.zip" ]]; then
                  hash=$(sha256sum "deployment_package.zip" | cut -d' ' -f1)
                  echo "deployment_package.zip: ${hash}" >> ../package-hashes.txt
                fi

            - name: Upload Package Hashes
              uses: actions/upload-artifact@v4
              with:
                  name: package-hashes
                  path: ./package-hashes.txt
