name: Deployment Package Zip

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Install dependencies
              run: pip install -r requirements.txt -t ./deploy

            - name: Zip dependencies
              run: zip -r9 ./deploy/deployment_package.zip ./deploy

            - name: Zip files
              run: zip -r ./deploy/deployment_package.zip src/lambda/getTodoist.py src/lambda/putChatGPT.py src/lambda/putNotion.py src/lambda/getTodoist.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: deployment-package
                  path: ./deploy/deployment_package.zip
