name: Deploy with SSM Parameters

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: src/frontend/nextjs-app/package-lock.json

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}
        # Add audience explicitly for China regions or other non-default partitions
        audience: sts.amazonaws.com

    - name: Verify AWS Identity
      run: |
        echo "Verifying AWS credentials..."
        aws sts get-caller-identity
        echo "AWS credentials configured successfully"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
        terraform_wrapper: false

    - name: Determine environment
      id: env
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
        else
          echo "environment=dev" >> $GITHUB_OUTPUT
        fi

    - name: Terraform Init
      working-directory: main
      run: terraform init

    - name: Terraform Workspace
      working-directory: main
      run: terraform workspace select ${{ steps.env.outputs.environment }} || terraform workspace new ${{ steps.env.outputs.environment }}

    - name: Terraform Apply
      working-directory: main
      run: terraform apply -auto-approve

    - name: Sync Terraform Outputs to SSM
      run: |
        chmod +x scripts/sync-terraform-outputs-to-ssm.sh
        ./scripts/sync-terraform-outputs-to-ssm.sh --workspace ${{ steps.env.outputs.environment }}

    - name: Deploy Frontend
      run: |
        chmod +x scripts/deploy-frontend.sh
        ./scripts/deploy-frontend.sh --env ${{ steps.env.outputs.environment }}

    - name: Deployment Summary
      run: |
        echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Environment: ${{ steps.env.outputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- Time: $(date)" >> $GITHUB_STEP_SUMMARY
