name: Deployment Package Zip

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Include getTodoist
              run: cp src/lambda/getTodoist.py ./deploy
    
            - name: Include putTodoist
              run: cp src/lambda/putTodoist.py ./deploy
    
            - name: Include putChatGPT
              run: cp src/lambda/putChatGPT.py ./deploy
    
            - name: Include putNotion
              run: cp src/lambda/putNotion.py ./deploy
          
            - name: Install dependencies
              run: pip install -r requirements.txt -t ./deploy

            - name: Zip dependencies
              run: zip -r9 ./deploy/deployment_package.zip ./deploy
              working-directory: ./deploy

            - name: Zip files
              run: zip -r ./deployment_package.zip ./getTodoist.py ./putChatGPT.py ./putNotion.py ./getTodoist.py
              working-directory: ./deploy

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: deployment-package
                  path: ./deploy/deployment_package.zip
