name: Deployment Package Zip

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Create target directory
              run: mkdir -p deploy/visualization

            - name: Include lambda files
              run: |
                # First copy the Python files from the root lambda directory
                find src/lambda -maxdepth 1 -name "*.py" -exec cp {} ./deploy/ \;

                # Then copy the visualization Python files
                find src/lambda/visualization -name "*.py" -exec cp {} ./deploy/visualization/ \;

            - name: Include system_prompts
              run: |
                # Handle system_prompts directory which may contain files
                if [ -d "src/system_prompts" ]; then
                  find src/system_prompts -type f -exec cp {} ./deploy/ \;
                fi

            - name: Install dependencies
              run: pip install -r requirements.txt -t ./deploy

            - name: Zip dependencies
              run: zip -r9 ./deployment_package.zip ./
              working-directory: ./deploy

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: deployment-package
                  path: ./deploy/deployment_package.zip
