name: Deploy Frontend React App

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'src/frontend/react-app/**'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read   # Required for actions/checkout

env:
  AWS_REGION: 'us-east-2'  # Update to match your S3 bucket region
  NODE_VERSION: '18'
  ENVIRONMENT: >-
    ${{
      github.ref == 'refs/heads/main' && 'prod' ||
      'dev'
    }}

jobs:
  deploy:
    name: Build and Deploy React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'src/frontend/react-app/package-lock.json'

      - name: Install dependencies
        working-directory: src/frontend/react-app
        run: npm ci

      - name: Build React app
        working-directory: src/frontend/react-app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get S3 bucket name
        id: get-bucket
        run: |
          # Use AWS CLI to get the output value from CloudFormation/SSM parameter
          BUCKET_NAME=$(aws ssm get-parameter --name "/wyatt-personal-aws-${{ env.ENVIRONMENT }}/frontend_bucket_name" --query "Parameter.Value" --output text)
          echo "s3_bucket=${BUCKET_NAME}" >> $GITHUB_OUTPUT

          # Get CloudFront distribution ID
          CF_ID=$(aws ssm get-parameter --name "/wyatt-personal-aws-${{ env.ENVIRONMENT }}/cloudfront_id" --query "Parameter.Value" --output text || echo '')
          if [ -n "$CF_ID" ]; then
            echo "cloudfront_id=${CF_ID}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy static assets to S3 with cache headers
        run: |
          echo "Deploying static assets to bucket: ${{ steps.get-bucket.outputs.s3_bucket }}"
          aws s3 sync src/frontend/react-app/build/ s3://${{ steps.get-bucket.outputs.s3_bucket }}/ \
            --delete \
            --cache-control "max-age=31536000,public" \
            --exclude "*.html" \
            --exclude "*.json"

      - name: Deploy HTML and JSON files with no-cache headers
        run: |
          echo "Deploying HTML and JSON files to bucket: ${{ steps.get-bucket.outputs.s3_bucket }}"
          aws s3 sync src/frontend/react-app/build/ s3://${{ steps.get-bucket.outputs.s3_bucket }}/ \
            --cache-control "max-age=0,no-cache,no-store,must-revalidate" \
            --include "*.html" \
            --include "*.json"

      - name: Invalidate CloudFront cache
        if: steps.get-bucket.outputs.cloudfront_id != ''
        run: |
          echo "Invalidating CloudFront distribution: ${{ steps.get-bucket.outputs.cloudfront_id }}"
          aws cloudfront create-invalidation \
            --distribution-id ${{ steps.get-bucket.outputs.cloudfront_id }} \
            --paths "/*"
