name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'src/frontend/nextjs-app/**'
      - '.github/workflows/nextjs-deploy.yml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'src/frontend/nextjs-app/**'
      - '.github/workflows/nextjs-deploy.yml'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/frontend/nextjs-app/package-lock.json

      - name: Install dependencies
        working-directory: src/frontend/nextjs-app
        run: npm ci

      - name: Run linter
        working-directory: src/frontend/nextjs-app
        run: npm run lint

      - name: Run type check
        working-directory: src/frontend/nextjs-app
        run: npx tsc --noEmit

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: src/frontend/nextjs-app
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: src/frontend/nextjs-app
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: src/frontend/nextjs-app
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
          echo "Preview URL: $(cat deployment-url.txt)"

      - name: Comment PR with Preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const url = fs.readFileSync('src/frontend/nextjs-app/deployment-url.txt', 'utf8').trim();
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment ready!\n\nVisit: ${url}`
            });

  deploy-production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/frontend/nextjs-app/package-lock.json

      - name: Install dependencies
        working-directory: src/frontend/nextjs-app
        run: npm ci

      - name: Run linter
        working-directory: src/frontend/nextjs-app
        run: npm run lint

      - name: Run type check
        working-directory: src/frontend/nextjs-app
        run: npx tsc --noEmit

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: src/frontend/nextjs-app
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: src/frontend/nextjs-app
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: src/frontend/nextjs-app
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
