name: Configure SSM Parameters for Deployment

on:
  # Trigger automatically after successful Terraform apply
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed
    branches:
      - main
      - dev

  # Keep manual trigger option for testing
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to configure (dev or prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: read   # Required for actions/checkout
  id-token: write  # Required for OIDC authentication

env:
  AWS_REGION: 'us-east-2'  # Update to match your AWS region

jobs:
  set-ssm-parameters:
    name: Set SSM Parameters
    runs-on: ubuntu-latest
    # Only run if manually triggered OR if Terraform apply was successful
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Determine Environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
            echo "Manual trigger - Environment: ${{ github.event.inputs.environment }}"
          elif [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            # Determine environment based on the branch that triggered Terraform apply
            if [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
              echo "environment=prod" >> $GITHUB_OUTPUT
              echo "Auto trigger from main branch - Environment: prod"
            else
              echo "environment=dev" >> $GITHUB_OUTPUT
              echo "Auto trigger from dev branch - Environment: dev"
            fi
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # For workflow_run events, checkout the triggering branch
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use dynamic role ARN construction with AWS_ACCOUNT_ID secret
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-oidc-role-${{ steps.env.outputs.environment }}
          role-session-name: GitHubActionsDeployment
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false

      - name: Verify AWS Identity
        run: |
          echo "Verifying AWS credentials..."
          aws sts get-caller-identity
          echo "AWS credentials configured successfully"

      - name: Get Terraform outputs
        id: terraform-outputs
        run: |
          cd main

          # Initialize Terraform to access state
          terraform init

          # Check if we can get Cognito User Pool ID directly from Terraform
          USER_POOL_ID=$(terraform output -raw cognito_user_pool_id 2>/dev/null || echo "")
          CLIENT_ID=$(terraform output -raw cognito_client_id 2>/dev/null || echo "")
          API_ENDPOINT=$(terraform output -raw api_endpoint 2>/dev/null || echo "")
          FRONTEND_BUCKET=$(terraform output -raw website_bucket_name 2>/dev/null || echo "")
          CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id 2>/dev/null || echo "")

          # Store the values
          echo "user_pool_id=${USER_POOL_ID}" >> $GITHUB_OUTPUT
          echo "client_id=${CLIENT_ID}" >> $GITHUB_OUTPUT
          echo "api_endpoint=${API_ENDPOINT}" >> $GITHUB_OUTPUT
          echo "frontend_bucket=${FRONTEND_BUCKET}" >> $GITHUB_OUTPUT
          echo "cloudfront_id=${CLOUDFRONT_ID}" >> $GITHUB_OUTPUT

      - name: Set up S3 bucket parameter
        run: |
          # Use Terraform output if available, otherwise do lookup
          if [ -n "${{ steps.terraform-outputs.outputs.frontend_bucket }}" ]; then
            BUCKET_NAME="${{ steps.terraform-outputs.outputs.frontend_bucket }}"
          else
            BUCKET_NAME=$(aws s3api list-buckets --query "Buckets[?contains(Name, 'wyatt-personal-aws-${{ steps.env.outputs.environment }}-app')].Name | [0]" --output text)
          fi

          echo "Found bucket: $BUCKET_NAME"

          # Store bucket name in SSM Parameter Store
          aws ssm put-parameter \
            --name "/wyatt-personal-aws-${{ steps.env.outputs.environment }}/frontend_bucket_name" \
            --value "$BUCKET_NAME" \
            --type "String" \
            --overwrite

          echo "S3 bucket parameter set successfully"

      - name: Set up CloudFront distribution parameter
        run: |
          # Use Terraform output if available, otherwise do lookup
          if [ -n "${{ steps.terraform-outputs.outputs.cloudfront_id }}" ]; then
            CF_ID="${{ steps.terraform-outputs.outputs.cloudfront_id }}"
          else
            # Get bucket name for lookup
            BUCKET_NAME=$(aws ssm get-parameter --name "/wyatt-personal-aws-${{ steps.env.outputs.environment }}/frontend_bucket_name" --query "Parameter.Value" --output text)

            # Find CloudFront distribution that has our bucket as origin
            BUCKET_DOMAIN=$(aws s3api get-bucket-location --bucket "$BUCKET_NAME" --query "join('.', ['s3', LocationConstraint])" --output text)
            if [ "$BUCKET_DOMAIN" = "s3.null" ]; then
              BUCKET_DOMAIN="s3.us-east-1.amazonaws.com"
            fi

            BUCKET_ORIGIN="${BUCKET_NAME}.${BUCKET_DOMAIN}"
            echo "Looking for CloudFront distribution with origin containing: $BUCKET_ORIGIN"

            CF_ID=$(aws cloudfront list-distributions \
              --query "DistributionList.Items[?Origins.Items[?contains(DomainName, '$BUCKET_NAME')]].Id | [0]" \
              --output text)
          fi

          if [ "$CF_ID" != "None" ] && [ -n "$CF_ID" ]; then
            echo "Found CloudFront distribution: $CF_ID"

            # Store CloudFront ID in SSM Parameter Store
            aws ssm put-parameter \
              --name "/wyatt-personal-aws-${{ steps.env.outputs.environment }}/cloudfront_id" \
              --value "$CF_ID" \
              --type "String" \
              --overwrite

            echo "CloudFront ID parameter set successfully"
          else
            echo "No CloudFront distribution found for bucket"
          fi

      - name: Set up Cognito User Pool parameters
        run: |
          # Use Terraform output if available
          if [ -n "${{ steps.terraform-outputs.outputs.user_pool_id }}" ]; then
            USER_POOL_ID="${{ steps.terraform-outputs.outputs.user_pool_id }}"
            echo "Found User Pool ID: $USER_POOL_ID"

            # Store User Pool ID in SSM Parameter Store
            aws ssm put-parameter \
              --name "/wyatt-personal-aws-${{ steps.env.outputs.environment }}/cognito_user_pool_id" \
              --value "$USER_POOL_ID" \
              --type "String" \
              --overwrite

            echo "Cognito User Pool ID parameter set successfully"
          else
            echo "No User Pool ID found from Terraform outputs"
          fi

          # Use Terraform output if available
          if [ -n "${{ steps.terraform-outputs.outputs.client_id }}" ]; then
            CLIENT_ID="${{ steps.terraform-outputs.outputs.client_id }}"
            echo "Found Client ID: $CLIENT_ID"

            # Store Client ID in SSM Parameter Store
            aws ssm put-parameter \
              --name "/wyatt-personal-aws-${{ steps.env.outputs.environment }}/cognito_client_id" \
              --value "$CLIENT_ID" \
              --type "String" \
              --overwrite

            echo "Cognito Client ID parameter set successfully"
          else
            echo "No Client ID found from Terraform outputs"
          fi

      - name: Set up API Gateway endpoint parameter
        run: |
          # Use Terraform output if available
          if [ -n "${{ steps.terraform-outputs.outputs.api_endpoint }}" ]; then
            API_ENDPOINT="${{ steps.terraform-outputs.outputs.api_endpoint }}"
            echo "Found API Endpoint: $API_ENDPOINT"

            # Store API Endpoint in SSM Parameter Store
            aws ssm put-parameter \
              --name "/wyatt-personal-aws-${{ steps.env.outputs.environment }}/api_endpoint" \
              --value "$API_ENDPOINT" \
              --type "String" \
              --overwrite

            echo "API Endpoint parameter set successfully"
          else
            echo "No API Endpoint found from Terraform outputs"
          fi

      - name: Deployment Summary
        run: |
          echo "## SSM Parameters Configuration Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ steps.env.outputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            echo "- **Triggered by**: ${{ github.event.workflow_run.name }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Source branch**: ${{ github.event.workflow_run.head_branch }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "- **Timestamp**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ SSM parameters updated successfully for **${{ steps.env.outputs.environment }}** environment" >> $GITHUB_STEP_SUMMARY
